# Write your MySQL query statement below
SELECT
    ST.STUDENT_ID,
    ST.STUDENT_NAME,
    SU.SUBJECT_NAME,
    COALESCE(EX.ATTENDED_EXAMS, 0) AS ATTENDED_EXAMS
FROM STUDENTS ST
INNER JOIN SUBJECTS SU
    ON 1 = 1
LEFT JOIN (
    SELECT
        STUDENT_ID,
        SUBJECT_NAME,
        COUNT(*) AS ATTENDED_EXAMS
    FROM EXAMINATIONS
    GROUP BY STUDENT_ID, SUBJECT_NAME
) AS EX
    ON ST.STUDENT_ID = EX.STUDENT_ID 
        AND SU.SUBJECT_NAME = EX.SUBJECT_NAME
ORDER BY ST.STUDENT_ID, SU.SUBJECT_NAME
;