# Write your MySQL query statement below
SELECT 
    PP1.PRODUCT_ID AS PRODUCT1_ID,
    PP2.PRODUCT_ID AS PRODUCT2_ID,
    PI1.CATEGORY AS PRODUCT1_CATEGORY,
    PI2.CATEGORY AS PRODUCT2_CATEGORY,
    COUNT(PP1.USER_ID) AS CUSTOMER_COUNT
FROM PRODUCTPURCHASES PP1
INNER JOIN PRODUCTPURCHASES PP2
    ON PP1.USER_ID = PP2.USER_ID
    AND PP1.PRODUCT_ID < PP2.PRODUCT_ID
LEFT JOIN PRODUCTINFO PI1
    ON PP1.PRODUCT_ID = PI1.PRODUCT_ID
LEFT JOIN PRODUCTINFO PI2
    ON PP2.PRODUCT_ID = PI2.PRODUCT_ID
GROUP BY PRODUCT1_ID, PRODUCT2_ID
HAVING COUNT(PP1.USER_ID) >= 3
ORDER BY CUSTOMER_COUNT DESC, PRODUCT1_ID ASC, PRODUCT2_ID ASC
;