# Write your MySQL query statement below
SELECT
    NAME,
    COALESCE(TRAVELLED_DISTANCE, 0) AS TRAVELLED_DISTANCE 
FROM USERS U
LEFT JOIN (
    SELECT
        USER_ID,
        SUM(DISTANCE) AS TRAVELLED_DISTANCE
    FROM RIDES
    GROUP BY USER_ID
) R
    ON U.ID = R.USER_ID
ORDER BY TRAVELLED_DISTANCE DESC, NAME ASC
;