# Write your MySQL query statement below
# 2019-08-16 이전에 값이 있는 PRODUCT는 마지막 PRICE를 가져옴
SELECT
    PRODUCT_ID, 
    NEW_PRICE AS PRICE
FROM PRODUCTS
WHERE (PRODUCT_ID, CHANGE_DATE) IN (
    SELECT
        PRODUCT_ID,
        MAX(CHANGE_DATE)
    FROM PRODUCTS
    WHERE CHANGE_DATE <= "2019-08-16"
    GROUP BY PRODUCT_ID
)

UNION
# 2019-08-16 이전에 값이 없는 PRODUCT의 PRICE는 10
SELECT
    PRODUCT_ID,
    10 AS PRICE
FROM PRODUCTS
GROUP BY PRODUCT_ID
HAVING MIN(CHANGE_DATE) > "2019-08-16"
;