/*
Enter your query here.
*/
SELECT
    MAX(CASE WHEN OCCUPATION = "DOCTOR" THEN NAME ELSE NULL END),
    MAX(CASE WHEN OCCUPATION = "PROFESSOR" THEN NAME ELSE NULL END),
    MAX(CASE WHEN OCCUPATION = "SINGER" THEN NAME ELSE NULL END),
    MAX(CASE WHEN OCCUPATION = "ACTOR" THEN NAME ELSE NULL END)
FROM (
    SELECT
        NAME,
        OCCUPATION,
        RANK() OVER(PARTITION BY OCCUPATION ORDER BY NAME ASC) AS RANKING
    FROM OCCUPATIONS
) AS SUBQUERY
GROUP BY RANKING
;