/*
Enter your query here.
*/
SELECT
    MAX(CASE WHEN OCCUPATION = "Doctor" THEN NAME ELSE NULL END),
    MAX(CASE WHEN OCCUPATION = "Professor" THEN NAME ELSE NULL END),
    MAX(CASE WHEN OCCUPATION = "Singer" THEN NAME ELSE NULL END),
    MAX(CASE WHEN OCCUPATION = "Actor" THEN NAME ELSE NULL END)
FROM (
    SELECT
        NAME,
        OCCUPATION,
        RANK() OVER(PARTITION BY OCCUPATION ORDER BY NAME ASC) AS RANKING
    FROM OCCUPATIONS
) AS SUBQUERY
GROUP BY RANKING
;