# Write your MySQL query statement below
SELECT
    S.USER_ID,
    COALESCE(ROUND(SUM(CASE WHEN C.ACTION="CONFIRMED" THEN 1 ELSE 0 END)/COUNT(C.ACTION), 2), 0) AS CONFIRMATION_RATE
FROM SIGNUPS S
LEFT JOIN CONFIRMATIONS C
    ON S.USER_ID = C.USER_ID
GROUP BY S.USER_ID
;