# Write your MySQL query statement below
SELECT
    S.USER_ID,
    COALESCE(ROUND(CONFIRMED_CNT/TOTAL_CNT, 2), 0) AS CONFIRMATION_RATE
FROM SIGNUPS S
LEFT JOIN (
    SELECT 
        USER_ID,
        COUNT(ACTION) AS CONFIRMED_CNT
    FROM CONFIRMATIONS
    WHERE ACTION = "CONFIRMED"
    GROUP BY USER_ID, ACTION
) C1
    ON S.USER_ID = C1.USER_ID
LEFT JOIN (
    SELECT
        USER_ID,
        COUNT(ACTION) AS TOTAL_CNT
    FROM CONFIRMATIONS
    GROUP BY USER_ID
) AS C2
    ON S.USER_ID = C2.USER_ID
GROUP BY S.USER_ID, C1.CONFIRMED_CNT, C2.TOTAL_CNT
;