# Write your MySQL query statement below
SELECT 
	P.PRODUCT_ID,
	COALESCE(ROUND(AVG(U.UNITS * P.PRICE)/AVG(U.UNITS), 2), 0) AS AVERAGE_PRICE
FROM PRICES P
LEFT JOIN UNITSSOLD U
	ON U.PURCHASE_DATE BETWEEN P.START_DATE AND P.END_DATE
AND U.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID
;