-- 코드를 입력하세요
SELECT 
    YEAR(OS.SALES_DATE) AS YEAR,
    MONTH(OS.SALES_DATE) AS MONTH,
    COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT OS.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE JOINED LIKE "2021-%"), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE OS
WHERE USER_ID IN (
    SELECT DISTINCT USER_ID
    FROM USER_INFO
    WHERE JOINED LIKE "2021-%"
)
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
;