# Write your MySQL query statement below
SELECT
	R.CONTEST_ID,
    ROUND(COUNT(R.USER_ID) / (SELECT COUNT(USER_ID) FROM USERS) * 100, 2) AS PERCENTAGE
FROM REGISTER R
LEFT JOIN USERS U
	ON R.USER_ID = U.USER_ID
GROUP BY R.CONTEST_ID
ORDER BY PERCENTAGE DESC, R.CONTEST_ID ASC
;