# Write your MySQL query statement below
SELECT 
    DEPARTMENT,
    EMPLOYEE,
    SALARY
FROM (
    SELECT
        D.NAME AS DEPARTMENT,
        E.NAME AS EMPLOYEE,
        E.SALARY AS SALARY,
        RANK() OVER(PARTITION BY D.ID ORDER BY E.SALARY DESC) AS RANKING
    FROM EMPLOYEE E
    INNER JOIN DEPARTMENT D
        ON E.DEPARTMENTID = D.ID
) AS SUBQUERY
WHERE RANKING = 1
;