/*
Enter your query here.
*/
SELECT
    HA.HACKER_ID,
    HA.NAME
FROM SUBMISSIONS SU
INNER JOIN HACKERS HA
    ON SU.HACKER_ID = HA.HACKER_ID
INNER JOIN CHALLENGES CH
    ON SU.CHALLENGE_ID = CH.CHALLENGE_ID
INNER JOIN DIFFICULTY DI
    ON CH.DIFFICULTY_LEVEL = DI.DIFFICULTY_LEVEL AND SU.SCORE = DI.SCORE
GROUP BY HA.HACKER_ID, HA.NAME
HAVING COUNT(HA.HACKER_ID) >= 2
ORDER BY COUNT(HA.HACKER_ID) DESC, HA.HACKER_ID ASC
;