-- 코드를 입력하세요
SELECT
    HISTORY_ID,
    ROUND(DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * (1 - IF(DISCOUNT_RATE IS NULL, 0, DISCOUNT_RATE)/100), 0) AS FEE
FROM (
    SELECT 
        HISTORY_ID,
        CAR_ID,
        START_DATE, 
        END_DATE,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN "90일 이상"
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN "30일 이상"
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN "7일 이상"
            ELSE ""
        END AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) CRCRH
INNER JOIN CAR_RENTAL_COMPANY_CAR CRCC
    ON CRCRH.CAR_ID = CRCC.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
    ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE AND CRCRH.DURATION = CRCDP.DURATION_TYPE
WHERE CRCC.CAR_TYPE = "트럭"
ORDER BY FEE DESC, HISTORY_ID DESC
;