# Write your MySQL query statement below
(SELECT U.NAME AS RESULTS
FROM MOVIERATING MR
INNER JOIN USERS U
    ON MR.USER_ID = U.USER_ID
GROUP BY U.USER_ID, U.NAME
ORDER BY COUNT(U.USER_ID) DESC, NAME ASC
LIMIT 1)

UNION ALL

(SELECT M.TITLE AS RESULTS
FROM MOVIERATING MR
INNER JOIN MOVIES M
    ON MR.MOVIE_ID = M.MOVIE_ID
WHERE MR.CREATED_AT LIKE "2020-02%"
GROUP BY MR.MOVIE_ID, M.TITLE
ORDER BY AVG(RATING) DESC, M.TITLE ASC
LIMIT 1)
;