# Write your MySQL query statement below
SELECT 
    P.PRODUCT_NAME,
    SUM(O.UNIT) AS UNIT
FROM PRODUCTS P
INNER JOIN ORDERS O
    ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.ORDER_DATE LIKE "2020-02%"
GROUP BY PRODUCT_NAME
HAVING SUM(O.UNIT) >= 100
;