-- 코드를 작성해주세요
SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II
LEFT JOIN ITEM_TREE IT ON II.ITEM_ID = IT.PARENT_ITEM_ID
WHERE IT.PARENT_ITEM_ID IS NULL
ORDER BY II.ITEM_ID DESC
;
-- OR
# SELECT ITEM_ID, ITEM_NAME, RARITY
# FROM ITEM_INFO
# WHERE ITEM_ID NOT IN (
#     SELECT PARENT_ITEM_ID
#     FROM ITEM_TREE
#     WHERE PARENT_ITEM_ID IS NOT NULL
# )
# ORDER BY ITEM_ID DESC
# ;