# Write your MySQL query statement below
SELECT *
FROM (
    SELECT
        VISITED_ON,
        SUM(AMOUNT) OVER(ORDER BY VISITED_ON ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS AMOUNT,
        ROUND(AVG(AMOUNT) OVER(ORDER BY VISITED_ON ROWS BETWEEN 6 PRECEDING AND CURRENT ROW), 2) AS AVERAGE_AMOUNT
    FROM (
        SELECT 
            VISITED_ON,
            SUM(AMOUNT) AS AMOUNT
        FROM CUSTOMER
        GROUP BY VISITED_ON
    ) AS SUBA
) AS SUBB
WHERE VISITED_ON >= DATE_ADD(
    (
        SELECT MIN(VISITED_ON)
        FROM CUSTOMER
    ), INTERVAL 6 DAY
)
ORDER BY VISITED_ON ASC
;