# Write your MySQL query statement below
SELECT PERSON_NAME
FROM (
    SELECT
        PERSON_NAME,
        SUM(WEIGHT) OVER(ORDER BY TURN) AS TOTAL_WEIGHT
    FROM QUEUE
) AS SUBQUERY
WHERE TOTAL_WEIGHT <= 1000
ORDER BY TOTAL_WEIGHT DESC
LIMIT 1
;