# Write your MySQL query statement below
SELECT
    U.NAME,
    SUM(T.AMOUNT) AS BALANCE
FROM USERS U
INNER JOIN TRANSACTIONS T
    ON U.ACCOUNT = T.ACCOUNT
GROUP BY T.ACCOUNT
HAVING SUM(T.AMOUNT) > 10000
;