/*
Enter your query here.
*/
SELECT
    W.ID,
    WP.AGE,
    W.COINS_NEEDED,
    W.POWER
FROM WANDS W
INNER JOIN WANDS_PROPERTY WP
    ON W.CODE = WP.CODE AND WP.IS_EVIL = 0
WHERE W.COINS_NEEDED = (
    SELECT MIN(COINS_NEEDED)
    FROM WANDS W2
    INNER JOIN WANDS_PROPERTY WP2
        ON W2.CODE = WP2.CODE AND WP2.IS_EVIL = 0
    WHERE W.POWER = W2.POWER AND WP.AGE = WP2.AGE
)
ORDER BY W.POWER DESC, WP.AGE DESC
;