# Write your MySQL query statement below
SELECT
    USER_ID,
    ROUND(AVG(CASE WHEN ACTIVITY_TYPE = "FREE_TRIAL" AND USER_ID IN (SELECT USER_ID FROM USERACTIVITY WHERE ACTIVITY_TYPE = "PAID") THEN ACTIVITY_DURATION END), 2) AS TRIAL_AVG_DURATION,
    ROUND(AVG(CASE WHEN ACTIVITY_TYPE = "PAID" THEN ACTIVITY_DURATION END), 2) AS PAID_AVG_DURATION
FROM USERACTIVITY
GROUP BY USER_ID
HAVING TRIAL_AVG_DURATION IS NOT NULL OR PAID_AVG_DURATION IS NOT NULL
ORDER BY USER_ID ASC
;