/*
Enter your query here.
MYSQL 8.0 이상 버전에서 동작
*/
SELECT 
    SUB1.SUBMISSION_DATE, 
    SUB1.HACKER_COUNT,
    SUB2.HACKER_ID,
    H.NAME
FROM (
    SELECT
        SUBMISSION_DATE,
        COUNT(DISTINCT HACKER_ID) AS HACKER_COUNT
    FROM SUBMISSIONS S1
    GROUP BY SUBMISSION_DATE
) SUB1
INNER JOIN (
    SELECT
        SUBMISSION_DATE,
        HACKER_ID,
        ROW_NUMBER() OVER(PARTITION BY SUBMISSION_DATE ORDER BY CNT DESC, HACKER_ID ASC) AS RANKING
    FROM (
        SELECT
            SUBMISSION_DATE,
            HACKER_ID,
            COUNT(*) AS CNT
        FROM SUBMISSIONS
        GROUP BY SUBMISSION_DATE, HACKER_ID
    ) S
) SUB2
    ON SUB1.SUBMISSION_DATE = SUB2.SUBMISSION_DATE
INNER JOIN HACKERS H
    ON SUB2.HACKER_ID = H.HACKER_ID
WHERE SUB2.RANKING = 1
ORDER BY SUB1.SUBMISSION_DATE ASC;
