/*
Enter your query here.
*/
CREATE TABLE PRIME(NUM INTEGER);

DELIMITER $$
CREATE PROCEDURE INSERTNUM()
BEGIN
    DECLARE I INT DEFAULT 2;
    WHILE I <= 1000 DO
        INSERT INTO PRIME VALUES(I);
        SET I = I+1;
    END WHILE;
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE DELETENUM()
BEGIN
    DECLARE I INT DEFAULT 2;
    WHILE I <= 500 DO
        DELETE FROM PRIME WHERE NUM % I = 0 AND NUM/I > 1;
        SET I = I+1;
    END WHILE;
END $$
DELIMITER ;



CALL INSERTNUM();
CALL DELETENUM();

SELECT GROUP_CONCAT(NUM SEPARATOR "&") FROM PRIME;