-- 코드를 입력하세요
# SELECT USER_ID, PRODUCT_ID
# FROM ONLINE_SALE
# GROUP BY USER_ID, PRODUCT_ID
# HAVING COUNT(*) >= 2
# ORDER BY USER_ID ASC, PRODUCT_ID DESC
# ;

-- 셀프 조인 사용
SELECT A.USER_ID, A.PRODUCT_ID
FROM ONLINE_SALE A
INNER JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID AND A.PRODUCT_ID = B.PRODUCT_ID
WHERE A.SALES_DATE != B.SALES_DATE
GROUP BY A.USER_ID, A.PRODUCT_ID
ORDER BY A.USER_ID ASC, A.PRODUCT_ID DESC
;
