-- 코드를 작성해주세요
-- 다른 스킬들도 가질 수 있기 때문에 = 대신 LIKE 사용
SELECT 
    CASE
        WHEN GROUP_CONCAT(S.NAME) LIKE "%Python%" AND GROUP_CONCAT(S.CATEGORY) LIKE "%Front End%" THEN "A"
        WHEN GROUP_CONCAT(S.NAME) LIKE "%C#%" THEN "B"
        WHEN GROUP_CONCAT(S.CATEGORY) LIKE "%Front End%" THEN "C"
    END AS GRADE,
    D.ID,
    D.EMAIL
FROM SKILLCODES S
INNER JOIN DEVELOPERS D
    ON (S.CODE & D.SKILL_CODE = S.CODE)
GROUP BY D.ID, D.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE ASC, D.ID ASC
;
