/*
Enter your query here.
*/
SELECT
    HA.HACKER_ID,
    NAME,
    COUNT(CHALLENGE_ID) AS CHALLENGE_CREATED
FROM CHALLENGES CH
INNER JOIN HACKERS HA
    ON CH.HACKER_ID = HA.HACKER_ID
GROUP BY HA.HACKER_ID, NAME
HAVING CHALLENGE_CREATED IN (
    SELECT CHALLENGE_CREATED
    FROM (
        SELECT HACKER_ID, COUNT(CHALLENGE_ID) AS CHALLENGE_CREATED
        FROM CHALLENGES
        GROUP BY HACKER_ID
    ) SUB
    GROUP BY CHALLENGE_CREATED
    HAVING COUNT(CHALLENGE_CREATED) = 1
) OR CHALLENGE_CREATED IN (
    SELECT MAX(CHALLENGE_CREATED)
    FROM (
        SELECT HACKER_ID, COUNT(CHALLENGE_ID) AS CHALLENGE_CREATED
        FROM CHALLENGES
        GROUP BY HACKER_ID
    ) SUB
)
ORDER BY CHALLENGE_CREATED DESC, HA.HACKER_ID ASC
;