# Write your MySQL query statement below
(SELECT
    "Low Salary" AS CATEGORY,
    SUM(CASE WHEN INCOME < 20000 THEN 1 ELSE 0 END) AS ACCOUNTS_COUNT
FROM ACCOUNTS)
UNION ALL
(SELECT
    "Average Salary" AS CATEGORY,
    SUM(CASE WHEN INCOME >= 20000 AND INCOME <= 50000 THEN 1 ELSE 0 END) AS ACCOUNTS_COUNT
FROM ACCOUNTS)
UNION ALL
(SELECT
    "High Salary" AS CATEGORY,
    SUM(CASE WHEN INCOME > 50000 THEN 1 ELSE 0 END) AS ACCOUNTS_COUNT
FROM ACCOUNTS)
;