# Write your MySQL query statement below
SELECT
    ROUND(SUM(TARGET_CNT)/COUNT(DISTINCT PLAYER_ID), 2) AS FRACTION
FROM (
    SELECT 
        PLAYER_ID,
        CASE 
            WHEN EVENT_DATE = DATE_ADD(MIN(EVENT_DATE) OVER (PARTITION BY PLAYER_ID), INTERVAL 1 DAY) THEN 1 
            ELSE 0 
        END AS TARGET_CNT
    FROM ACTIVITY
) AS SUBQUERY
;