# Write your MySQL query statement below
SELECT
    SAMPLE_ID,
    DNA_SEQUENCE,
    SPECIES,
    DNA_SEQUENCE REGEXP "^ATG" AS HAS_START,
    DNA_SEQUENCE REGEXP "TAA$|TAG$|TGA$" AS HAS_STOP,
    DNA_SEQUENCE REGEXP "ATAT" AS HAS_ATAT,
    DNA_SEQUENCE REGEXP "GGG" AS HAS_GGG
FROM SAMPLES
ORDER BY SAMPLE_ID ASC
;