# Write your MySQL query statement below
SELECT ROUND(SUM(TIV_2016), 2) AS tiv_2016
FROM INSURANCE I
WHERE TIV_2015 IN (
    SELECT TIV_2015
    FROM INSURANCE
    WHERE PID != I.PID
) AND (LAT, LON) NOT IN (
    SELECT LAT, LON
    FROM INSURANCE
    WHERE PID != I.PID
)
;