/*
Enter your query here.
*/
SELECT
    HA.HACKER_ID,
    NAME,
    SUM(SCORE) AS TOTAL_SCORE
FROM HACKERS HA
INNER JOIN (
    SELECT HACKER_ID, MAX(SCORE) AS SCORE
    FROM SUBMISSIONS
    GROUP BY HACKER_ID, CHALLENGE_ID
) SUB
    ON HA.HACKER_ID = SUB.HACKER_ID
GROUP BY HA.HACKER_ID, NAME
HAVING TOTAL_SCORE != 0
ORDER BY TOTAL_SCORE DESC, HA.HACKER_ID ASC
;