/*
Enter your query here.
*/
SELECT
    HA.HACKER_ID,
    HA.NAME,
    SUM(SCORE) AS TOTAL_SCORE
FROM HACKERS HA
INNER JOIN (
    SELECT 
        HACKER_ID,
        CHALLENGE_ID,
        MAX(SCORE) AS SCORE
    FROM SUBMISSIONS
    GROUP BY HACKER_ID, CHALLENGE_ID
) SU
ON HA.HACKER_ID = SU.HACKER_ID
GROUP BY HA.HACKER_ID, HA.NAME
HAVING TOTAL_SCORE != 0
ORDER BY TOTAL_SCORE DESC, HA.HACKER_ID ASC
;