-- 코드를 입력하세요
SELECT CRCC.CAR_ID, CRCC.CAR_TYPE, ROUND(CRCC.DAILY_FEE * (1-CRCDP.DISCOUNT_RATE/100) * 30, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CRCC
INNER JOIN (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = "30일 이상"
) CRCDP ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE
WHERE CRCC.CAR_TYPE IN ("세단", "SUV")
    AND CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= "2022-11-30" AND END_DATE > "2022-11-01"
    )
    AND CRCC.DAILY_FEE * (1-CRCDP.DISCOUNT_RATE/100) * 30 >= 500000
    AND CRCC.DAILY_FEE * (1-CRCDP.DISCOUNT_RATE/100) * 30 < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
;