-- 코드를 작성해주세요
SELECT GRANDCHILD.ID
FROM ECOLI_DATA GRANDCHILD
INNER JOIN (
    SELECT CHILD.ID
    FROM ECOLI_DATA CHILD
    INNER JOIN ECOLI_DATA PARENT
        ON CHILD.PARENT_ID = PARENT.ID
    WHERE PARENT.PARENT_ID IS NULL
) PPARENT
    ON GRANDCHILD.PARENT_ID = PPARENT.ID
GROUP BY GRANDCHILD.ID
ORDER BY GRANDCHILD.ID ASC
;