/*
Enter your query here.
*/
SELECT
    CON.CONTEST_ID,
    HACKER_ID,
    NAME,
    IF(SUM(STS) IS NULL, 0, SUM(STS)) AS SSTS,
    IF(SUM(STAS) IS NULL, 0, SUM(STAS)) AS SSTAS,
    IF(SUM(STV) IS NULL, 0, SUM(STV)) AS SSTV,
    IF(SUM(STUV) IS NULL, 0, SUM(STUV)) AS SSTUV
FROM CONTESTS CON
LEFT JOIN COLLEGES COL
    ON CON.CONTEST_ID = COL.CONTEST_ID
LEFT JOIN CHALLENGES CHA
    ON COL.COLLEGE_ID = CHA.COLLEGE_ID
LEFT JOIN (
    SELECT 
        CHALLENGE_ID,
        SUM(TOTAL_SUBMISSIONS) AS STS,
        SUM(TOTAL_ACCEPTED_SUBMISSIONS) AS STAS
    FROM SUBMISSION_STATS
    GROUP BY CHALLENGE_ID
) SUB
    ON CHA.CHALLENGE_ID = SUB.CHALLENGE_ID
LEFT JOIN (
    SELECT
        CHALLENGE_ID,
        SUM(TOTAL_VIEWS) AS STV,
        SUM(TOTAL_UNIQUE_VIEWS) AS STUV
    FROM VIEW_STATS
    GROUP BY CHALLENGE_ID
) VIE
    ON CHA.CHALLENGE_ID = VIE.CHALLENGE_ID
GROUP BY CON.CONTEST_ID, HACKER_ID, NAME
HAVING SSTS + SSTAS + SSTV + SSTUV > 0
ORDER BY CON.CONTEST_ID ASC
;
