# Write your MySQL query statement below
SELECT
    ID,
    SUM(CASE WHEN MONTH="JAN" THEN REVENUE END) AS Jan_Revenue,
    SUM(CASE WHEN MONTH="FEB" THEN REVENUE END) AS Feb_Revenue,
    SUM(CASE WHEN MONTH="MAR" THEN REVENUE END) AS Mar_Revenue,
    SUM(CASE WHEN MONTH="APR" THEN REVENUE END) AS Apr_Revenue,
    SUM(CASE WHEN MONTH="MAY" THEN REVENUE END) AS May_Revenue,
    SUM(CASE WHEN MONTH="JUN" THEN REVENUE END) AS Jun_Revenue,
    SUM(CASE WHEN MONTH="JUL" THEN REVENUE END) AS Jul_Revenue,
    SUM(CASE WHEN MONTH="AUG" THEN REVENUE END) AS Aug_Revenue,
    SUM(CASE WHEN MONTH="SEP" THEN REVENUE END) AS Sep_Revenue,
    SUM(CASE WHEN MONTH="OCT" THEN REVENUE END) AS Oct_Revenue,
    SUM(CASE WHEN MONTH="NOV" THEN REVENUE END) AS Nov_Revenue,
    SUM(CASE WHEN MONTH="DEC" THEN REVENUE END) AS Dec_Revenue
FROM DEPARTMENT
GROUP BY ID
;