/*
Enter your query here.
*/
SELECT NAME
FROM STUDENTS S
INNER JOIN FRIENDS F
    ON S.ID = F.ID
INNER JOIN PACKAGES P
    ON F.FRIEND_ID = P.ID
WHERE P.SALARY > (
    SELECT SALARY
    FROM PACKAGES
    WHERE S.ID = ID
)
ORDER BY P.SALARY ASC
;