/*
Enter your query here.
*/
SELECT
    IF(GRADE >= 8, NAME, NULL) AS NAME,
    GRADE,
    MARKS
FROM STUDENTS ST
INNER JOIN GRADES GR
    ON ST.MARKS >= MIN_MARK AND ST.MARKS <= MAX_MARK
ORDER BY GRADE DESC, NAME ASC, MARKS ASC
;